name: Build Docker App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Docker
      uses: docker/setup-buildx-action@v2

    - name: Construir imagen Docker
      run: docker build -t clasificador-onnx .

    - name: Verificar ejecución
      run: echo "Imagen construida correctamente ✅"

    - name: Configurar variables de entorno para producción (si es necesario)
      run: echo "APP_ENV=prod" >> $GITHUB_ENV