name: Test ONNX model

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Descargar modelo ONNX
      run: |
        curl -L -o regnet.onnx https://github.com/onnx/models/raw/main/Computer_Vision/regnet_x_16gf_Opset18_torch_hub/regnet_x_16gf_Opset18.onnx

    - name: Ejecutar pruebas con pytest
      run: pytest test_model_utils.py